"""
TradeOS Database Package
"""

from database.connection import (
    Base,
    DatabaseTransaction,
    check_database_health,
    close_database,
    execute_raw_query,
    get_db_context,
    get_db_session,
    get_engine,
    get_session_maker,
    init_database,
)
from database.models import (
    ApiKey,
    ApiKeyPermission,
    BacktestResult,
    MarketData,
    Order,
    OrderStatus,
    OrderType,
    Position,
    PositionSide,
    RiskProfile,
    Strategy,
    StrategyType,
    Subscription,
    SubscriptionStatus,
    SubscriptionTier,
    TimeFrame,
    Trade,
    TradeSide,
    TradeStatus,
    User,
    UserRole,
)

__all__ = [
    # Connection
    "Base",
    "get_engine",
    "get_session_maker",
    "get_db_session",
    "get_db_context",
    "init_database",
    "close_database",
    "check_database_health",
    "execute_raw_query",
    "DatabaseTransaction",
    # Models
    "User",
    "UserRole",
    "Strategy",
    "StrategyType",
    "Trade",
    "TradeSide",
    "TradeStatus",
    "Position",
    "PositionSide",
    "MarketData",
    "TimeFrame",
    "Order",
    "OrderType",
    "OrderStatus",
    "RiskProfile",
    "Subscription",
    "SubscriptionTier",
    "SubscriptionStatus",
    "ApiKey",
    "ApiKeyPermission",
    "BacktestResult",
]
